export const languageConstants = {
  en: {
    search: "Search",
    gptSearchPlaceHolder: "What would you like to watch today?",
    play: "▶️ Play",
    moreInfo: "More Info",
    nowPlaying: "Now Playing",
    topRated: "Top Rated",
    popular: "Popular",
    upcoming: "Upcoming",
    title: "Deadpool & Wolverine",
    overview:
      "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
    gptSearch: "GPT Search",
    logOut: "Logout",
    logOutContent: "Are you sure you want to sign out?",
    signOut: "Sign Out",
    homePage: "Homepage",
  },
  telugu: {
    search: "శోధన",
    gptSearchPlaceHolder: "మీరు ఈరోజు ఏమి చూడాలనుకుంటున్నారు?",
    play: "▶️ ప్రారంభం",
    moreInfo: "మరింత సమాచారం",
    nowPlaying: "ఇప్పుడు ప్లే అవుతోంది",
    topRated: "టాప్ రేటింగ్",
    popular: "జనాదరణ పొందినది",
    upcoming: "రాబోయేది",
    title: "డెడ్‌పూల్ & వుల్వరైన్",
    overview:
      "నీతిలేని వాడే విల్సన్ తన వెనుక నైతికంగా అనువైన కిరాయి సైనికుడు డెడ్‌పూల్‌గా పౌర జీవితంలో కష్టపడుతున్నాడు. కానీ అతని స్వస్థలం అస్తిత్వ ముప్పును ఎదుర్కొన్నప్పుడు, వాడే అయిష్టంగానే మరింత అయిష్టంగా ఉన్న వుల్వరైన్‌తో మళ్లీ సూట్ అప్ చేయాలి.",
    gptSearch: "జిపిటి శోధన",
    logOut: "లాగ్అవుట్",
    logOutContent: "మీరు ఖచ్చితంగా సైన్ అవుట్ చేయాలనుకుంటున్నారా?",
    signOut: "సైన్ అవుట్ చేయండి",
    homePage: "హోమ్‌పేజీ",
  },
  hindi: {
    search: "खोज",
    gptSearchPlaceHolder: "आज आप क्या देखना चाहेंगे?",
    play: "▶️ प्रारंभ करें",
    moreInfo: "और जानकारी",
    nowPlaying: "अब खेल रहे हैं",
    topRated: "टॉप रेटेड",
    popular: "लोकप्रिय",
    upcoming: "आगामी",
    title: "डेडपूल और वूल्वरिन",
    overview:
      "एक उदासीन वेड विल्सन नैतिक रूप से लचीले भाड़े के सैनिक, डेडपूल के रूप में अपने दिनों के साथ नागरिक जीवन में कड़ी मेहनत करता है। लेकिन जब उसके गृह जगत को अस्तित्व संबंधी ख़तरे का सामना करना पड़ता है, तो वेड को अनिच्छा से फिर से और भी अधिक अनिच्छुक वूल्वरिन के साथ जुड़ना पड़ता है।",
    gptSearch: "जीपीटी खोज",
    logOut: "लॉग आउट",
    logOutContent: "क्या आप द्वारा साइन आउट किया जाना सुनिश्चित है?",
    signOut: "साइन आउट",
    homePage: "मुखपृष्ठ",
  },
  spanish: {
    search: "buscar",
    gptSearchPlaceHolder: "¿Qué te gustaría ver hoy?",
    play: "▶️ Iniciar",
    moreInfo: "Más información",
    nowPlaying: "Ahora jugando",
    topRated: "Mejor valorados",
    popular: "Popular",
    upcoming: "Próximo",
    title: "Deadpool y Lobezno",
    overview:
      "Un Wade Wilson apático se esfuerza en la vida civil dejando atrás sus días como mercenario moralmente flexible, Deadpool. Pero cuando su mundo natal se enfrenta a una amenaza existencial, Wade debe volver a ponerse el traje a regañadientes con un Wolverine aún más reacio.",
    gptSearch: "Búsqueda GPT",
    logOut: "cerrar sesión",
    logOutContent: "¿Estás seguro de que quieres cerrar sesión?",
    signOut: "Desconectar",
    homePage: "Página principal",
  },
};
